### ISSUE TITLE
Having Trade Cycling in a server prevents it from starting up.

### ISSUE THREAD

**Issue by TeraBitGaming** [henkelmax/trade-cycling#1]
**Bug description**
Can't load a server with trade cycling installed.

**Steps to reproduce the issue**
1. Have/make a server
2. Try to launch it with Trade Cycling

**Expected behavior**
Server starts normally, happiness, rainbows and rabbits ensue.

**Log files**
https://gist.github.com/TeraBitGaming/1c3f6bcbaaf34bca0ec4b0f7e36b1b74

**Versions**
- Minecraft version: 1.18.1
- Forge version: 39.0.1
- Mod version: 1.0.0

**Other mods**
None others were reported in the crash.
screenshot of the used mods:
https://i.imgur.com/Pb1W3sC.png

**Comment by henkelmax** [comment]
Thanks for reporting this issue! It should be fixed in the next version.
