### ISSUE TITLE
mod is not working

### ISSUE THREAD

**Issue by Anormalman1** [henkelmax/trade-cycling#13]
**Bug description**
the mod is not working

**Steps to reproduce the issue**
I install the mod and is not working

**Expected behavior**
I expected to work

**Log files**
idk where and idk if I have because it not give me any error

**Versions**
- 1.19.4
- fabric - 0.14.21
- 1.0.5

**Other mods**
I the foto
![image](https://github.com/henkelmax/trade-cycling/assets/85508784/3a6ca342-36aa-4226-9fb7-fac8297c5a2f)

**Comment by henkelmax** [comment]
Please send the server and client logs like stated in the template.
Also please describe your issue. "not working" is not helpful at all.

**Comment by Anormalman1** [comment]
i can use this mod as a client mod and the mod don't need to be on the server

**Comment by henkelmax** [comment]
> i can use this mod as a client mod and the mod don't need to be on the server?

No
