### ISSUE TITLE
no 1.20 fabric release

### ISSUE THREAD

**Issue by tlaselbat** [henkelmax/trade-cycling#16]
will there be a 1.20 fabric release soon?

**Comment by KaroYT** [comment]
> We moved on to 1.20.1. There won't be anything for 1.20.

But forge 1.20 is available, only fabric isn't. Please, release it, it'll save a lot of time.

**Comment by henkelmax** [comment]
You can compile it from source yourself.

**Comment by DamnUi** [comment]
> You can compile it from source yourself. Or just update. There is really no reason to stay on that version.

im kind of new to all this and i too need the 1.20 java fabric edition so i dont mind compiling from source myself but how would i?

**Comment by DamnUi** [comment]
oh i found an alternative for it! @KaroYT  https://www.curseforge.com/minecraft/mc-mods/retraining/files?version=1.20 works
