### ISSUE TITLE
No reroll of trades

### ISSUE THREAD

**Issue by 4kKoZ** [henkelmax/trade-cycling#18]
Basically i click on the icon to refresh trades, and it just plays the sound but no rerolls

1. find a villager and give it a job
2.click on the button so its suppose to refresh the trade

I expected that when i was going to click that the trade was going to refresh just like the GIF in the forge website

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).    idk how to get log files but idk if u need em

**Versions**
- Minecraft version: 1.20.1
- Forge/Fabric loader version: fabric 1.20.1
- Mod version: [FABRIC][1.20.1] Trade Cycling 1.20.1-1.0.5

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue. no need for screenshot ig
<img width="694" alt="Screenshot 2023-08-15 at 1 34 19 AM" src="https://github.com/henkelmax/trade-cycling/assets/136613764/2c801ee8-3ec7-4bce-b3e7-07980353ec29">
<img width="703" alt="Screenshot 2023-08-15 at 1 34 31 AM" src="https://github.com/henkelmax/trade-cycling/assets/136613764/361ea1d5-68be-4652-9283-e89b92750cea">
<img width="699" alt="Screenshot 2023-08-15 at 1 34 42 AM" src="https://github.com/henkelmax/trade-cycling/assets/136613764/a2532fb1-7d9e-4983-be67-4d0f8144cb86">
<img width="675" alt="Screenshot 2023-08-15 at 1 34 51 AM" src="https://github.com/henkelmax/trade-cycling/assets/136613764/353817b0-a947-41ea-abbe-0fc8fe3c2427">

here is all my mods that im using

**Comment by henkelmax** [comment]
I need the logs

**Comment by henkelmax** [comment]
Closed due to inactivity
