### ISSUE TITLE
[Feature Request] Set reroll goals, and automatically disable reroll button when goal is met

### ISSUE THREAD

**Issue by zhguyu** [henkelmax/trade-cycling#19]
The ability to add goals for the wanted trade(s), and temporarily disable (gray out) the reroll button when one of the goals is met. The button would be re-enabled the next time the trade GUI is opened so players still have the choice to reroll if they are not happy with the current result somehow.
In this way players would be able to just click the button blindly until it's disabled so they know the desired trade appears.

**Comment by henkelmax** [comment]
I don't know if this will still be necessary with the upcoming villager changes.
