### ISSUE TITLE
[Feature request] Option to reroll trades after first one is completed

### ISSUE THREAD

**Issue by chrisatola** [henkelmax/trade-cycling#20]
Would it be possible to create a config option for rerolling trades even after you've made the first one? For example, the herdsman always seems to want the rarest wool colours, the ones I always have the least of. Being able to sell what I do have and then reroll in hopes of a different colour popping up would make levelling up traders so much easier.

**Comment by henkelmax** [comment]
No. This mod uses the same mechanics as vanilla minecraft does. This would be way too overpowered.
