### ISSUE TITLE
Mod works on local world but not on hosted instance.

### ISSUE THREAD

**Issue by Sylencia** [henkelmax/trade-cycling#23]
**Bug description**
I have Trade Cycling added on both server and client, but the mod only works once per session on the hosted instance.
When I try the same thing on a local world the mod works fine.

**Steps to reproduce the issue**
1. Add mod to hosted server. (and have it on client)
2. Get a librarian with no trades done.
3. Confirm you can do trade cycling.
4. Close the window and open it again (without trading before closing).
5. The trade cycling arrow no longer appears.

**Expected behavior**
The trade cycling arrow should remain shown

**Log files**
I have checked the logs but there was no output related to trade cycling. As mentioned, it also works fine on a local world. Let me know if I still need to have a log uploaded

**Versions**
- Minecraft version 1.20.4
- Mod loader - Fabric
- Mod loader version - 0.15.3
- Mod version - 1.20.4-1.0.11

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

![image](https://github.com/henkelmax/trade-cycling/assets/9345990/95796acc-a770-4e62-9b22-6cba7f349fe5)

I have tested it on the server with nothing but Fabric API + Trade Cycling on that end.
I have also tested it with the client only having Fabric API + Trade Cycling.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Please provide logs, like stated in the template.

**Comment by Sylencia** [comment]
Client log can be found here: https://gist.github.com/Sylencia/eba75bcf317afc4a7f0885a9e49fbfb3
Server log can be found here: https://gist.github.com/Sylencia/a8732d8c671ed0761dd997772ed64be8

**Comment by henkelmax** [comment]
I tried it on a server with just the mod installed and it works perfectly fine.
Are there any steps needed to reproduce the issue?

**Comment by Sylencia** [comment]
I don't think so, I recently moved my server hosting but in both places it wasn't working. I do know the mod worked while I was in 1.20.1, but broke when I updated.

I'll try to give you my configuration setup to see if anything odd sticks out, but I will be away this weekend so I'll only be able to do it in a few days time

**Comment by Sylencia** [comment]
I'm wondering if there are any server configs I should look out for as far as you know - I tried an experiment today where I downloaded  a backup of my server and ran it locally. This worked fine and the arrow was showing up as expected. Hopefully this narrows it down a little bit.

**Comment by henkelmax** [comment]
was your backup missing anythig?

**Comment by Sylencia** [comment]
No it was a full backup. How does the trade button location config set the location? I couldn't find a place to set it and am wondering if maybe it's somehow changing from the default to none?

**Comment by Sylencia** [comment]
FWIW, the mod still works with the keybind setting - I only just tested that now after discovering it existed from the code 😆

**Comment by henkelmax** [comment]
Ok, so it seems to be a client side issue. Did you change any mods on the client or something when testing with the backup?

**Comment by Sylencia** [comment]
I tried to keep things consistent so I kept the mod list the same on the client when testing with the backup

**Comment by Sylencia** [comment]
I tried it with the client side having only Fabric API + Trade cycling and it seems to still only work in local. I've put the video here if you want to check my methodology: https://youtu.be/Px6X1EcdUmE

**Comment by henkelmax** [comment]
Thanks for the video. I'll try to reproduce it on an actual server.

**Comment by henkelmax** [comment]
Just tested it on a server with latest Fabric loader and latest mod version. Same on the client and it works fine. Even after reconnecting or restarting the game.
Did you try connecting to another server with the mod or just test it with another villager in another area?

**Comment by henkelmax** [comment]
Closed due to inactivity.

**Comment by EgorDoomsday** [comment]
Also found this issue in my survival world. And got a "fix" for this.
After logging into world, trade cycling button disappears after 1-2 seconds.
Fixed this by disabling datapack "Blaze & Caves advancements" (or so)
Some datapack funtions seems to be listening to villlager's trade GUI in order to count trades (There are some achievements like "trade X times")
Also tried with only Fabric, Fabric API and Trade Cycling - same issue
Minecraft 1.20.4
Fabric loader 0.15.6
Fabric API 0.95.4
Trade Cycling 1.0.11
No other datapacks except this one

**Comment by Sylencia** [comment]
That would probably explain it (sorry for the inactivity, I didn't realise there was another question posted). I do have the Blaze and Caves achievements data pack and that probably has conflicts. At least the hotkey works so that's good enough.
