### ISSUE TITLE
Mending being added back to the list of cycled trades even though its being disabled by other mods/datapacks

### ISSUE THREAD

**Issue by silentSquid** [henkelmax/trade-cycling#26]
### Bug description

Hi there,

Sorry this is not really a bug but more of a compat issue so to say?
I'm trying to disable mending being available from villagers in 1.20 and it looks like Trade Cycling is adding it back even though its being disabled by things like https://modrinth.com/mod/balancing-for-better or https://www.planetminecraft.com/data-pack/no-mending-offers
Is there anything that can be done to prevent it?
Thanks!

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.7

### Mod loader and version

Fabric 15.7

### Steps to reproduce

1. added trade cycling
2. added Balancing-For-Better mod or no mending datapacks
3. cycled trades a bunch
4. mending still appears in trades

### Expected behavior

I don't want Mending to appear in cycled trades

### Log files

n/a

**Comment by henkelmax** [comment]
The mod does not change anything with villager trades. It just adds a button to cycle the trades, the same way as when removing the villagers workstation.
