### ISSUE TITLE
Trade Cycle button doesnt show up.

### ISSUE THREAD

**Issue by MasterCJ123** [henkelmax/trade-cycling#27]
### Bug description

It only shows up for a split second then disappears.

### Minecraft version

1.20.4

### Mod version

1.20.4

### Mod loader and version

Fabric & Forge

### Steps to reproduce

1. Load the game in Hardcore mode.
2. Find a villager
3. Try and trade with the villager

### Log files

https://gist.github.com/

### Screenshots

![2024-04-22_23 22 47](https://github.com/henkelmax/trade-cycling/assets/72818364/19aabc8c-c281-42a8-94a6-c9b0d3ae6ba5)

**Comment by henkelmax** [comment]
Please provide logs.
Does this happen without any other mods?
Are you playing on singleplayer or on a server?

**Comment by henkelmax** [comment]
Closed due to inactivity.
