### ISSUE TITLE
Cycle button appears for a split second and never again.

### ISSUE THREAD

**Issue by Jake-Norton** [henkelmax/trade-cycling#29]
### Bug description

When interacting with a villager that has accepted a profession for the first time, the cycle button can briefly be seen before disappearing. It does not reappear when closing and reopening the GUI.

### Minecraft version

1.21

### Mod version

1.21-1.0.12

### Mod loader and version

fabric-loader-0.15.11-1.21

### Steps to reproduce

Interact with any villager that has not yet been traded with.

### Expected behavior

I expect to be able to use the mod's primary function.

### Log files

https://gist.github.com/Jake-Norton/8fc53336a23ced3ffdc3f5ade91cdb0e

**Comment by henkelmax** [comment]
Do you have the mod installed on both server and client?

**Comment by Jake-Norton** [comment]
It's singleplayer, so yes.

**Comment by henkelmax** [comment]
Does that happen without any other mods installed?

**Comment by Jake-Norton** [comment]
Just did a bunch of testing, looks like the conflict was actually with one of my datapacks. I'm not sure how that works, but good to know it's on my end at least. Apologies for the time wasted.
