### ISSUE TITLE
[Fabric, 1.19.2] Mason cycle button

### ISSUE THREAD

**Issue by TheSnowyChickens** [henkelmax/trade-cycling#3]
**Bug description**
Hello,
the cycle button don't work with the mason.

**Steps to reproduce the issue**
1. Place a stonecutter
2. Summon a Villager
3. *magic* Mason Villager 
4. Click  the cycle button and nothing will change

**Expected behavior**
New trades

**Log files**
https://pastebin.com/YGFETEBS
(these are the log files in a larger modpack, but I tested it with a small test pack with the mods below)

**Versions**
- 1.19.2
- Fabric: 0.14.9
- trade-cycling-fabric-1.19.2-1.0.5

**Other mods**
![grafik](https://user-images.githubusercontent.com/29357962/192010494-2f2eb42f-4758-4fa0-acb8-eedc166f41f4.png)

**Screenshots (Optional)**
![grafik](https://user-images.githubusercontent.com/29357962/192010545-1ebd4fbc-404c-4e0a-a00a-1fb9a81cbb32.png)

**Comment by henkelmax** [comment]
The mason only has these trades at that level:

![image](https://user-images.githubusercontent.com/13237524/192010865-b59f743d-413b-4080-ace6-1991dbfab462.png)

**Comment by TheSnowyChickens** [comment]
Oh, can you maybe blacklist the mason from the cycle button ?

**Comment by henkelmax** [comment]
No
