### ISSUE TITLE
Trade cycle button disappears instantly

### ISSUE THREAD

**Issue by Laguna726** [henkelmax/trade-cycling#34]
### Bug description

When opening a villager's trade menu, the cycle button shows up fine and functions properly the first time. However, after trading once it vanishes, and any attempt to reopen the menu to get it to reappear will result in it only showing up for a split second, making it impossible to use.

I saw that somebody had a similar issue on here, but after testing, this is the only mod I have enabled and no external mods or data packs are interfering with this mod's functionality. Also, I've noticed that other mods with this trade cycle feature tend to have the same issue, such as Wunderreich.

### Minecraft version

1.21

### Mod version

1.21.1-1.0.14

### Mod loader and version

Fabric Loader 0.16.0

### Steps to reproduce

Interact with a villager that has been previously traded with prior.

### Expected behavior

When I open the villager trading menu at any point and after trading multiple times the trade cycle icon is meant to show up and function properly

### Log files

https://gist.github.com/Laguna726/86a8f32440ecd5f766c280ef48989d6a#file-gistfile1-txt

### Screenshots

![Screenshot (66)](https://github.com/user-attachments/assets/8b0e8f5e-7c86-4eba-8e26-1c77223386b9)
![Screenshot (67)](https://github.com/user-attachments/assets/2a1acde4-4af4-4df2-b213-e074ec45a5ae)

**Comment by henkelmax** [comment]
Thats the whole point. you cant cycle trades of a villager that has been traded with. Thats the same way it works in vanilla.
