### ISSUE TITLE
Multiplayer?

### ISSUE THREAD

**Issue by GoejserXD** [henkelmax/trade-cycling#37]
### Bug description

The mod doesn't work on any multiplayer sever
I dont know if its supposed to work if not it would be nice if it could be added

### Minecraft version

1.21.1

### Mod version

1.0.14

### Mod loader and version

[FABRIC][1.21.1] Trade Cycling 1.21.1-1.0.14

### Steps to reproduce

1. join multiplayer 2. try it on villager 3. it doesn't work

### Expected behavior

you press the button and nothing happens

### Log files

https://gist.github.com/.

**Comment by henkelmax** [comment]
You need to have the mod installed on both client and server.
