### ISSUE TITLE
Cant Cycle Trades on Server

### ISSUE THREAD

**Issue by wo11yy** [henkelmax/trade-cycling#39]
### Bug description

The mod works as expected on singleplayer. But when i join my server with the exact same modlist and I open a villagers trade menu I can see the cycle button for a split second before it goes away and does not come back.

### Minecraft version

1.21

### Mod version

1.21.1-1.0.14

### Mod loader and version

Prism Launcher 8.4 Fabric Loader 0.16.5

### Steps to reproduce

1. Join fresh server
2. Find villager
3. Open menu
4. No cycle button
5. Go to singleplayer
6. repeat 2+3
7. Its there

### Expected behavior

To be able to trade cycle

### Log files

https://gist.github.com/wo11yy/871e826406a11f373e33ca4d644e89ed

### Screenshots

![2024-10-10_10 42 20](https://github.com/user-attachments/assets/c3bee7e5-cd4d-4203-8467-7952ab2dc837)

https://github.com/user-attachments/assets/663cb513-fed5-4406-a898-4bc779803ffd

**Comment by wo11yy** [comment]
The screenshot is from singleplayer, the clip is from multiplayer

**Comment by henkelmax** [comment]
Works perfectly fine for me when doing your steps to reproduce. Please check if it happens without any other mods.

**Comment by ikon106** [comment]
I have the same issue. It worked for the first villager, but then no more. It also worked once for another villager, but then I get the same issue as above. Shows for a second and then disappears.

**Comment by wo11yy** [comment]
The hotkey works despite the button disappearing

**Comment by ikon106** [comment]
> This could be a compatibility issue with another mod. Please check if this happens without any other mods

It was Villager Names by Serilum that was the problem. I think it counts the named villagers as traded with.

**Comment by ikon106** [comment]
Is this possible to fix?
