### ISSUE TITLE
After Cycling, Villagers can't trade

### ISSUE THREAD

**Issue by StockingA-web** [henkelmax/trade-cycling#40]
### Bug description

After cycling trades, villagers refuses to trade. Villagers will shake their head and not letting us trade with them despite them having a job.

### Minecraft version

1.21.1

### Mod version

trade-cycling-fabric-1,21.1-1.0.15.jar

### Mod loader and version

Fabric 1.21.1 (0.16.5)

### Steps to reproduce

1. Rapidly trade cycle with button/keybind
2. Stop trade cycle and exit trade menu.
3. Wait 5 - 10 minutes 
4. Check back to villager 

### Log files

Log for Mod not found

### Screenshots

![2024-10-20_22 49 39](https://github.com/user-attachments/assets/755b4a17-00ef-448c-a0d0-96d596151d7b)

**Comment by henkelmax** [comment]
I am not able to reproduce your issue. Also try using villagers inside the trader block.
