### ISSUE TITLE
Cycling doesnt work

### ISSUE THREAD

**Issue by TwxsterYT** [henkelmax/trade-cycling#41]
### Bug description

When i cycle the trade, i just get "kicked" out of the trading menu but when i try to trade with the villager again nothing opens so i cant trade with him. The villager keeps his appearence after cycling the trade but i cant trade with him after cycling. To trade again i have to break the job block.

### Minecraft version

1.21.1

### Mod version

1.0.15

### Mod loader and version

Fabric Loader 0.16.9

### Steps to reproduce

1. Join a server
2. Try to trade with a villager
3. Cycle the trade
4. Try to trade with the villager again

### Expected behavior

The trade cycles, but that doesnt happen

### Log files

https://gist.github.com/TwxsterYT/8fac4da5eae1db4b8daab27f1ee1b65a

### Screenshots

https://github.com/user-attachments/assets/4648c069-708f-4ada-8b4f-e429124bea0d

**Comment by henkelmax** [comment]
I am not able to reproduce this issue. Does the same thing happen with just this mod installed on the client and server?

**Comment by TwxsterYT** [comment]
It just doesnt work on the server. When im in a singleplayer world it does work.

**Comment by henkelmax** [comment]
That wasn't what I asked though.

**Comment by TwxsterYT** [comment]
Oh sorry. The mod is installed on the server and the client.

**Comment by henkelmax** [comment]
> Does the same thing happen with just this mod installed on the client and server?

**Comment by TwxsterYT** [comment]
Yes. But only on the server not in singleplayer

**Comment by henkelmax** [comment]
Can you send me your client and server logs of that?

**Comment by TwxsterYT** [comment]
Hi! Sorry but how do I do that for the client? And I tested it with all the mods from the server on the client and its working too, so all the other mods that i had shouldnt be an issue.

**Comment by TwxsterYT** [comment]
Update: I dont know how but the mod breaks in combination with the ["Vanish"](https://modrinth.com/mod/vanish) mod. I said I removed all mods with i thought but after looking again the mod didnt disappear so that is a error on my side sorry. I dont know if youre still interested in this problem then.

**Comment by MCLeon-tests** [comment]
> Update: I dont know how but the mod breaks in combination with the ["Vanish"](https://modrinth.com/mod/vanish) mod. I said I removed all mods with i thought but after looking again the mod didnt disappear so that is a error on my side sorry. I dont know if youre still interested in this problem then.

Try using 1.5.6 (vanish then its working) had the same issue

**Comment by TwxsterYT** [comment]
> > Update: I dont know how but the mod breaks in combination with the ["Vanish"](https://modrinth.com/mod/vanish) mod. I said I removed all mods with i thought but after looking again the mod didnt disappear so that is a error on my side sorry. I dont know if youre still interested in this problem then.
> 
> Try using 1.5.6 (vanish then its working) had the same issue

I reported it to the mod author of vanish and he fixed it.

**Comment by MCLeon-tests** [comment]
Is it now fixed in the 1.5.7 ? (of vanish)
