### ISSUE TITLE
[1.18.2] Configs about Button Location

### ISSUE THREAD

**Issue by INooBTooMuch** [henkelmax/trade-cycling#5]
**Bug description**
I wanted to find the config file to change the button location (as is mentioned in the Curseforge page "Configurable trade cycling button location") but I wasn't able to find it in neither "config" not "serverconfig" folders so I use the [Configured](https://www.curseforge.com/minecraft/mc-mods/configured) mod to do it in-game and then crashed.
This might be a Feature for maybe only Fabric or 1.19.x but I didn't find anything more about it.

**Steps to reproduce the issue**
1. Go to mods
2. Select Trade Cycling  config
3. Change the location to None or Top Right
4. Save Changes
5. Crash

**Log files**
[Log](https://gist.github.com/INooBTooMuch/27d3cd7acc5d76a032bed946a3f45a53)
I found this line here : 
Caused by: java.lang.NullPointerException: Cannot invoke "com.electronwill.nightconfig.core.UnmodifiableCommentedConfig.configFormat()" because "config" is null
And on the Crash Screen :
Error: java.lang.NullPointerException: Cannot invoke "com.electronwill.nightconfig.core.UnmodifiableCommentedConfig.configFormat()" because "config" is null

**Versions**
- Minecraft version : 1.18.2
- Forge/Fabric version : Forge 40.1.80
- Mod version : 1.0.2

**Other mods**
Happens also with these mods:
Catalogue : 1.6.2
Configured : 1.5.4
Trade Cycling : 1.0.2

**Comment by henkelmax** [comment]
It seems that this crash happens with configured. Please try if it happens without that mod.

**Comment by INooBTooMuch** [comment]
Without that mod I wont be able to change the location, because I wan't able to find the config file for this mod. Tried searching for Trade and Cycling but only got the configs for other mods.
Maybe the name is something else and then I wouldn't need to change them while in-game

**Comment by henkelmax** [comment]
You can't change the config ingame. You need to adjust it in the config file.

**Comment by INooBTooMuch** [comment]
I can't find the file inside the config or the serverconfig files. That's why I used Configured but it causes the crash.
Do you know if the config doesn't load in 1.18.2 or the name isn't "trade-cycling" because searching it doesn't show up

**Comment by henkelmax** [comment]
`config/trade_cycling-client.toml`

**Comment by INooBTooMuch** [comment]
no doesn't show up

**Comment by henkelmax** [comment]
Its not on the server its on the client.

**Comment by INooBTooMuch** [comment]
yes im in the client

**Comment by henkelmax** [comment]
No clue what you are doing, but for me its there 100%

**Comment by INooBTooMuch** [comment]
I also tried with just trade cycling but this is the config folder:
![image](https://user-images.githubusercontent.com/107572028/192255491-6edd73d9-6ce7-4553-ae8c-1c8ba26968ff.png)
I don't know why its not downloading the config file

**Comment by henkelmax** [comment]
Can you send me the logs of that instance?

**Comment by INooBTooMuch** [comment]
https://gist.github.com/INooBTooMuch/27d3cd7acc5d76a032bed946a3f45a53#file-just-trade-cycling-i-believe

**Comment by henkelmax** [comment]
Nope, everything works perfectly fine here.

**Comment by INooBTooMuch** [comment]
I have no idea what is happening, but I guess the button stays top_left

**Comment by INooBTooMuch** [comment]
If I download the config and put it in the config folder with the correct name will that work?

**Comment by henkelmax** [comment]
Nope
