### ISSUE TITLE
doesnt work at all

### ISSUE THREAD

**Issue by RichPrune** [henkelmax/trade-cycling#9]
**Bug description**
when pressing the hotkey in the trading menu or trying to find the button in the trading menu the button is gone and the key does nothing no matter what its set to. You had one job.

**Steps to reproduce the issue**
1. Open 1.18.2 forge
2. Click on trading menu
4. Error

**Expected behavior**
Trade cycle function worked

**Log files**
Please provide log files of the game session in which the problem occurred.
attached below

**Versions**
- Minecraft version 1.18.2
- Forge/Fabric version 40.2.1
- Mod version one from 3/2; the only one on this version

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.
probably Quest Giver; the modpack is dawncraft and you have to do some fetch quests for villagers to gain reputation before you can trade

**Screenshots (Optional)**
Screenshots of the issue.
![2023-04-04_22 35 52](https://user-images.githubusercontent.com/103792572/229966796-530b9cfd-9f67-472c-b2ec-b413ab6c7138.png)

[latest.log](https://github.com/henkelmax/trade-cycling/files/11154687/latest.log)

**Comment by henkelmax** [comment]
Does that happen without any mods installed?
